module.exports = {
  DEPLOY_TOKEN_SUCCESS: "DEPLOY_TOKEN_SUCCESS",
  GET_AGENCY_SUCCESS: "GET_AGENCY_SUCCESS",
  LIST_SUCCESS: "LIST_SUCCESS",
  SET_LOADING: "SET_LOADING",
  RESET_LOADING: "RESET_LOADING",
};
