module.exports = {
	ADD_AID_SUCCESS: 'ADD_AID_SUCCESS',
	BENEF_LIST_SUCCSS: 'BENEFICIARY_LIST_SUCCESS',
	GET_AID_SUCCESS: 'GET_AID_SUCCESS',
	LIST_AID_SUCCESS: 'LIST_AID_SUCCESS',
	RESET_LOADING: 'RESET_LOADING',
	SET_LOADING: 'SET_LOADING',
	VENDORS_LIST_SUCCESS: 'VENDORS_LIST_SUCCESS',
	SET_TOTAL_TOKENS: 'SET_TOTAL_TOKENS',
	SET_AVAILABLE_TOKENS: 'SET_AVAILABLE_TOKENS'
};
