module.exports = {
  LIST: "LIST_BENEFICIARY",
  LIST_AID: "LIST_AID",
  SET_AID: "SET_AID",
  SET_BENEFICIARY: "SET_BENEFICIARY",
  ADD: "ADD_BENEFICIARY",
  REMOVE: "REMOVE_BENEFICIARY",
  UPDATE: "UPDATE_BENEFICIARY",
  GET: "GET_BENEFICIARY",
  SET_TOKEN_BALANCE: "SET_TOKEN_BALANCE",
};
