module.exports = {
  LIST: "LIST_MOBILIZER",
  LIST_AID: "LIST_AID",
  SET_AID: "SET_AID",
  SET_MOBILIZER: "SET_MOBILIZER",
  ADD: "ADD_MOBILIZER",
  REMOVE: "REMOVE_MOBILIZER",
  UPDATE: "UPDATE_MOBILIZER",
  GET: "GET_MOBILIZER",
  SET_LOADING: "set_mobilizer_loading",
  RESET_LOADING: "reset_mobilizer_reset_loading",
  MOBILIZER_TX: "MOBILIZER_TX_HISTORY",
};
